### ISSUE TITLE
how do i compile this?

### ISSUE THREAD

**Issue by darkitxu84** [malortie/hl-theyhunger#1]
Where Is the project files?

**Comment by malortie** [comment]
@darkitxu84

You must use [CMake](https://cmake.org/) to generate the Visual Studio projects.

Please refer to these pages for installation and building the code :

- [Installation](https://github.com/malortie/hl-theyhunger/blob/master/INSTALL.md)
- [Building the Code](https://github.com/malortie/hl-theyhunger/blob/master/BUILDING.md)

Ensure you have installed the original mod.
https://www.moddb.com/mods/they-hunger/downloads/they-hunger-1-2-and-3

After you have configured CMake, you can generate a Visual Studio solution from which you can launch the mod in Debug mode.

Note that only Windows platform is supported at this time.

**Comment by darkitxu84** [comment]
when compiling, I get errors about "mathlib.h" (specifically C4235)

**Comment by malortie** [comment]
I tested using the latest source code version and a fresh CMake configuration, generated a Visual Studio 2019 solution targeting platform Win32 and built project ALL_BUILD.

Both client.dll and einar.dll (client and server DLLs) compiled without warnings and errors.

Please, can you post your full build log from Visual Studio output window ?

**Comment by darkitxu84** [comment]
Oh, I can now compile the project successfully. I was using CMake wrong, I was building the project for x64 (I really don't know how to use CMake). Thanks anyway for the help!
